language: node_js
node_js:
  - "node"
install:
  - npm ci --dev
script: 
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch: master
  local-dir: dist
  fqdn: paulll.cc
  on:
    branch: src
cache:
  directories:
  - "$HOME/.npm"
