language: node_js
node_js:
  - "node"
before_script:
  - npm install -g stylus pug-cli
  - mkdir -p site/style
script: 
  - stylus --compress --out site/style style
  - pug --out site pubs
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true 
  target-branch: master
  local-dir: site
  on:
    branch: src
