language: node_js
node_js:
  - "node"
before_script:
  - npm install -g stylus pug-cli yamljs
  - mkdir -p site/style
script: 
  - stylus --compress --out site/style style
  - yaml2json projects.yml > site/projects.yml
  - pug -O site/projects.yml --out site views
  - cp -r assets/* site
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch: master
  local-dir: site
  fqdn: paulll.cc
  on:
    branch: src
