#!/bin/bash

rm -rf site
mkdir -p site/style
`pwd`/bin/lndir `pwd`/assets `pwd`/site

yaml2json projects.yml > site/projects.yml

stylus --compress --watch --out site/style style &
pug -O site/projects.yml --watch --out site views
